name: 'Prerelease Suffix to Compose The Version Format'

description: 'Action to find the specific suffix to compose the version format'

outputs:
  prerelease_suffix:
    description: "Prerelease suffix"
    value: ${{ steps.get-prerelease-suffix.outputs.prerelease_suffix }}

runs:
  using: "composite"
  steps:
    - name: Find the specific suffix to compose the version format
      run: |
        import re
        import os
        github_head_ref = "${{ github.head_ref }}"
        name_branch = github_head_ref.lower()
        suffix_array = re.findall("alpha|beta|prerelease", name_branch)
        env_file = os.getenv('GITHUB_ENV')
        with open(env_file, "a") as myfile:
          myfile.write("PRERELEASE=" + suffix_array[0])
      shell: python
  
    - name: Set prerelease suffix as output
      id: get-prerelease-suffix
      run: echo "::set-output name=prerelease_suffix::$(echo $PRERELEASE)"
      shell: bash